package main;

import pojo.BusinessSeat;
import pojo.CheckingAccount;
import pojo.Defender;
import pojo.EconomySeat;
import pojo.FirstClassSeat;
import pojo.Flight;
import pojo.Forward;
import pojo.Hotel;
import pojo.HotelRoom;
import pojo.Laptop;
import pojo.Midfielder;
import pojo.Product;
import pojo.SavingsAccount;
import pojo.SmartPhone;
import pojo.TGDD;
import pojo.Tablet;
import pojo.Team;

public class Main {
	public static void main(String[] args) {
		Product laptop = new Laptop();
		Laptop laptop1 = (Laptop)laptop;
		laptop1.setId(01);
		laptop1.setName("Acer");
		laptop1.setPrice(500);
		laptop1.setQuantity(5);
		laptop1.setProcessor("Intel Core i5");
		laptop1.setRam(8);
		laptop1.setDiscount(0.05);
		Product laptop2 = new Laptop("Intel core i7", 16);
		laptop2.setId(04);
		laptop2.setName("Asus");
		laptop2.setPrice(800);
		laptop2.setQuantity(10);
		laptop2.setDiscount(0.1);
		Product smartphone = new SmartPhone();
		SmartPhone smartphone1 = (SmartPhone)smartphone;
		smartphone1.setId(02);
		smartphone1.setName("Xiaomi");
		smartphone1.setPrice(200);
		smartphone1.setQuantity(8);
		smartphone1.setCameraQuantity("16 mega pixel");
		smartphone1.setDiscount((double)0.2);
		Product tablet = new Tablet();
		Tablet tablet1 = (Tablet)tablet;
		tablet1.setId(03);
		tablet1.setName("Samsung");
		tablet1.setPrice(300);
		tablet1.setQuantity(6);
		tablet1.setMonitor("12.2 inch");
		tablet1.setDiscount((double)0.3);
		TGDD tgdd = new TGDD();
		tgdd.getProducts().add(laptop2);
		tgdd.getProducts().add(tablet);
		tgdd.getProducts().add(smartphone);
		tgdd.getProducts().add(laptop);
		tgdd.display();
		System.out.println("");
		
		System.out.println("Football");
		Forward m10 = new Forward();
		m10.setName("Lionel Messi");
		m10.setPosition("RF");
		m10.setSkillLevel(110);
		m10.play("In the top of the team better than Ronaldo!");
		Midfielder d7 = new Midfielder();
		d7.setName("Kevin De Bruyne");
		d7.setPosition("MF");
		d7.setSkillLevel(96);
		d7.play("In the mid of the team behide Messi!");
		Defender p4 = new Defender();
		p4.setName("Pique");
		p4.setPosition("DF");
		p4.setSkillLevel(88);
		p4.play("In the bot of the team!");
		Team dreamTeam = new Team();
		dreamTeam.getPlayers().add(m10);
		dreamTeam.getPlayers().add(d7);
		dreamTeam.getPlayers().add(p4);
		dreamTeam.display();
		System.out.println();

		HotelRoom r = new HotelRoom(1, 8, 100, true);
		HotelRoom r1 = new HotelRoom(2, 4, 60, true);
		HotelRoom r2 = new HotelRoom(3, 10, 120, true);
		HotelRoom r3 = new HotelRoom(4, 2, 40, true);
		HotelRoom r4 = new HotelRoom(5, 2, 40, false);
		HotelRoom r5 = new HotelRoom(6, 2, 40, false);
		Hotel hotel = new Hotel();
		hotel.getHotelRooms().add(r);
		hotel.getHotelRooms().add(r1);
		hotel.getHotelRooms().add(r2);
		hotel.getHotelRooms().add(r3);
		hotel.getHotelRooms().add(r4);
		hotel.getHotelRooms().add(r5);
		hotel.display();
		System.out.println("Search");
		hotel.searchRoom(2);
		System.out.println("Book");
		System.out.println(hotel.bookRoom(4));
		System.out.println(hotel.bookRoom(1));
		hotel.display();
		System.out.println("Checkout");
		System.out.println(hotel.checkout(5));
		System.out.println(hotel.checkout(6));
		System.out.println(hotel.checkout(7));
		System.out.println(hotel.checkout(8));
		hotel.display();
		hotel.calculateRevenue();
		System.out.println();

		System.out.println("Banking");
		CheckingAccount checkingAccount = new CheckingAccount(88886666, 2000);
		CheckingAccount checkingAccount1 = new CheckingAccount(88888888, 100);
		SavingsAccount savingsAccount = new SavingsAccount(22224444, 10000);
		SavingsAccount savingsAccount1 = new SavingsAccount(22226666, 1000);
		checkingAccount.display();
		checkingAccount1.display();
		savingsAccount.display();
		savingsAccount1.display();
		checkingAccount.withDraw(200);
		checkingAccount1.withDraw(300);
		checkingAccount.deposit(-100);
		checkingAccount1.deposit(100);
		savingsAccount.withDraw(8000);
		savingsAccount1.withDraw(1200);
		savingsAccount.deposit(16000);
		;
		savingsAccount1.deposit(0);
		checkingAccount.display();
		checkingAccount1.display();
		savingsAccount.display();
		savingsAccount1.display();
		System.out.println();

		System.out.println("Fighting");
		EconomySeat economySeat = new EconomySeat(1, 100, true);
		economySeat.getFinalPrice(20);
		EconomySeat economySeat1 = new EconomySeat(2, 100, true);
		economySeat1.getFinalPrice(20);
		EconomySeat economySeat2 = new EconomySeat(3, 100, false);
		economySeat2.getFinalPrice(20);
		BusinessSeat businessSeat = new BusinessSeat(4, 250, true);
		businessSeat.getFinalPrice(100);
		BusinessSeat businessSeat1 = new BusinessSeat(5, 250, false);
		businessSeat1.getFinalPrice(100);
		BusinessSeat businessSeat2 = new BusinessSeat(6, 250, false);
		businessSeat2.getFinalPrice(100);
		FirstClassSeat firstClassSeat = new FirstClassSeat(7, 600, true);
		firstClassSeat.getFinalPrice(500);
		FirstClassSeat firstClassSeat1 = new FirstClassSeat(8, 600, true);
		firstClassSeat1.getFinalPrice(500);
		FirstClassSeat firstClassSeat2 = new FirstClassSeat(9, 600, true);	
		firstClassSeat2.getFinalPrice(500);
		Flight flight = new Flight();
		flight.getSeats().add(economySeat);
		flight.getSeats().add(economySeat1);
		flight.getSeats().add(economySeat2);
		flight.getSeats().add(businessSeat);
		flight.getSeats().add(businessSeat1);
		flight.getSeats().add(businessSeat2);
		flight.getSeats().add(firstClassSeat);
		flight.getSeats().add(firstClassSeat1);
		flight.getSeats().add(firstClassSeat2);
		flight.display();
		flight.calculateTotalRevenue();
		flight.bookSeat(1);
		flight.bookSeat(4);
		flight.bookSeat(9);
		flight.bookSeat(8);
		flight.bookSeat(8);
		flight.display();
		flight.calculateTotalRevenue();
	}
}
